config/routes.rb
Rails.application.routes.draw do

  root to: "tickets#index"

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: { registrations: "users/registrations" }
  resources :users, only: [:show]
  resources :tickets
  resources :lessons
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  validates_presence_of :name, :section

  has_many :tickets
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  belongs_to :lesson

  validates_presence_of :user_id, :lesson_id, :question

  scope :open, -> { where(closed: false) }
  scope :answered, -> { where(closed: true) }

  def take_ticket
    self.update(taken: true, taken_at: Time.new())
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => ["200x200#", :png], :thumb => ["64x64#", :png] }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name

  has_many :tickets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

  def index
    @lessons = Lesson.all
  end

  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = Lesson.new(lesson_params)
    if @lesson.save
      respond_to do |format|
        format.html { redirect_to lessons_path }
        format.js
      end
    end
  end

  def show
    @lesson = Lesson.find(params[:id])
  end

  def edit
    @lesson = Lesson.find(params[:id])
  end

  def update
    @lesson = Lesson.find(params[:id])
    @lesson.update(params[:lesson])
    respond_to do |format|
      format.html { redirect_to lessons_url }
      format.js
    end
  end

private

  def lesson_params
    params.require(:lesson).permit(:name, :section, :url)
  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

  def index
    @tickets = Ticket.all
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)
    if @ticket.save
      flash[:success] = "Help is on the way!"
      respond_to do |format|
        format.html { redirect_to tickets_path }
        format.js
      end
    end
  end

  def show
    @ticket = Ticket.find(params[:id])
  end

  def edit
    @ticket = Ticket.find(params[:id])
  end

  def update
    @ticket = Ticket.find(params[:id])
    @ticket.update(ticket_params)
    respond_to do |format|
      format.html { redirect_to @ticket }
      format.js
    end
  end

private

  def ticket_params
    params.require(:ticket).permit(:question, :lesson_id, :taken, :taken_at, :done, :done_at).merge(user_id: current_user.id)
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  before_filter :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :avatar)
    end
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :current_password, :avatar)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
  <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name %>" role="alert">
    <%= msg %>
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RavenApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= @user_form ? 'user-form-page' : ''%>">

<nav class="navbar navbar-default title-space" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">RAVEN</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to lessons_path do %>
              <span class="glyphicon glyphicon-list"></span> lessons
            <% end %>
          </li>
        <% if user_signed_in? %>
          <li>
            <%= link_to edit_user_registration_path do %>
              <span class="glyphicon glyphicon-user"></span> <%= current_user.name %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <span class="glyphicon glyphicon-log-out"></span> logout
            <% end %>
          </li>
        <% else %>
          <li><%= link_to "sign up", new_user_registration_path %></li>
          <li><%= link_to "login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

  <div class="container">
    <span id="flash-msg"></span>
    <%= yield %>
  </div>

</body>
</html>

app/views/lessons/_form.html.erb
<%= form_for @lesson, html: {class: "form"}, remote: true do |f| %>
<h2>Add a Lesson</h2>
  <%= render 'layouts/errors', :object => @lesson %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :url %>
    <%= f.text_field :url, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :section %>
    <%= f.text_field :section, class: "form-control" %>
  </div>

  <%= f.submit "Submit", class: "btn btn-lg btn-primary" %>
<% end %>

app/views/lessons/_lesson.html.erb
<%= link_to lesson_url(lesson), class: "list-group-item" do %>
  <% if lesson.tickets.count == 1 %>
    <span class="badge"><%= lesson.tickets.count %> ticket</span>
  <% else %>
    <span class="badge"><%= lesson.tickets.count %> tickets</span>
  <% end %>
  <h4 class="list-group-item-heading"><%= lesson.name %></h4>
  <p class="list-group-item-text"><%= lesson.section %></p>
<% end %>

app/views/lessons/create.js.erb
$('#new_lesson').remove();
$('#new_lesson_link').show();
$('#lessons_list').append('<%= j render(@lesson) %>');

app/views/lessons/index.html.erb
<div class="row">
  <div class="col-sm-6 col-md-6 col-sm-offset-3 col-md-offset-3">
    <div class="text-center">
      <br>
      <%= link_to "New Lesson", new_lesson_path, id: "new_lesson_link", class: "btn btn-lg btn-primary", remote: true %>
    </div>
  </div>
</div>
<br>
<br>
<div class="row">
  <div class="col-sm-6 col-md-6 col-sm-offset-3 col-md-offset-3">
    <div class="list-group" id="lessons_list">
      <%= render @lessons %>
    </div>
  </div>
</div>

app/views/lessons/new.js.erb
$('#new_lesson_link').hide().after('<%= j render("form") %>');

app/views/lessons/show.html.erb
<div class="col-sm-12 col-md-10 col-md-offset-1">
  <h1 class="page-header"><%= @lesson.name %> &nbsp;<small><%= @lesson.section %></small></h1>
  <p class="lead"><%= link_to "View Lesson", @lesson.url %></p>
  <br>
  <h2 class="page-header"><span class="glyphicon glyphicon-stats"></span> Stats</h2>
  <div class="row text-center">
    <div class="col-xs-6 col-sm-3">
      <h1><%= @lesson.tickets.count %></h1>
      <span class="text-muted">Total Tickets</span>
    </div>
    <div class="col-xs-6 col-sm-3 placeholder">
      <h1>#</h1>
      <span class="text-muted">Average Handle Time</span>
    </div>
    <div class="col-xs-6 col-sm-3 placeholder">
      <h1>#</h1>
      <span class="text-muted">Average Wait Time</span>
    </div>
    <div class="col-xs-6 col-sm-3 placeholder">
      <h1>#</h1>
      <span class="text-muted">Rank</span>
    </div>
  </div>
  <br><br>
  <h2 class="sub-header">Tickets</h2>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>id</th>
          <th>asked by</th>
          <th>wait time</th>
          <th>handle time</th>
          <th>date</th>
        </tr>
      </thead>
      <tbody>
        <% @lesson.tickets.each do |ticket| %>
        <tr>
          <td><%= ticket.id %></td>
          <td><%= ticket.user.name %></td>
          <td>#</td>
          <td>#</td>
          <td><%= ticket.created_at.getlocal.strftime('%F') %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/tickets/_form.html.erb
<script type="text/javascript">
  $('#raven').append('<%= image_tag "raven.png", class: "raven" %>');
  $('#raven').addClass('animated bounceInDown');
</script>

<div class="modal-dialog">
    <div class="modal-content">
      <%= form_for @ticket, html: {class: "form"}, remote: true do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title text-center" id="myModalLabel">Ask a Question</h4>
      </div>
      <div class="modal-body">
        <div id="raven" class="text-center">
        </div>
          <%= render 'layouts/errors', :object => @ticket %>
          <div class="form-group">
            <h3 class="text-left">What lesson are you on? &nbsp; <%= f.collection_select(:lesson_id, Lesson.all, :id, :name, multiple: true) %></h3>
          </div>

          <div class="form-group">
            <h3 class="text-left">Describe the issue you're having:</h3>
            <%= f.text_area :question, class: "form-control" %>
            <%= f.hidden_field :user_id, :value => current_user.id %>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-lg btn-default" data-dismiss="modal">Close</button>
        <%= f.submit "Dispatch the Raven!", class: "btn btn-lg btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>

app/views/tickets/_ticket.html.erb
<div class="row">
    <div class="media">
      <a class="pull-left" href="<%= user_url(ticket.user) %>">
        <%= image_tag ticket.user.avatar.url(:thumb), class: "media-object", alt: "#{ticket.user.name} avatar" %>
      </a>
      <div class="media-body">
        <h4 class="media-heading"><%= ticket.user.name %></h4>
        <p><%= link_to "#{truncate(ticket.question, length: 40, separator: ' ', escape: false)}", ticket_url(ticket), class: "lead" %></p>
        <p class="text-muted"><span class="glyphicon glyphicon-time"></span> <%= ticket.created_at.getlocal.strftime('%I:%M:%S %p // %F') %></p>
      </div>
    </div>
</div>

app/views/tickets/create.js.erb
$('#raven').removeClass('animated bounceInDown').addClass('animated fadeOutRight');
$('#tickets_list').append('<%= j render(@ticket) %>');
$("#ticket-modal").modal("hide");
$('#flash-msg').append('<%= j render("layouts/flash") %>');

app/views/tickets/index.html.erb
<div class="col-sm-10 col-md-offset-1 col-md-8 col-md-offset-2">
  <div class="text-center">
    <br>
      <%= link_to "Ask For Help", new_ticket_path, class: "btn btn-lg btn-primary", remote: true %>
  </div>
  <hr>
  <ul class="nav nav-tabs" role="tablist">
    <li><a href="#open" role="tab" data-toggle="tab">Open</a></li>
    <li><a href="#answered" role="tab" data-toggle="tab">Closed</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div class="tab-pane active" id="open">
      <div id="tickets_list">
        <%= render @tickets %>
      </div>
    </div>
    <div class="tab-pane" id="answered">
      <%= render @tickets %>
    </div>
  </div>
</div>
<div id="ticket-modal" class="modal fade"></div>

app/views/tickets/new.js.erb
$("#ticket-modal").html("<%= j render('form') %>");
$("#ticket-modal").modal("show");

app/views/tickets/show.html.erb
<div class="row">
  <div class="col-sm-10 col-md-offset-1 col-md-8 col-md-offset-2">
        <h4>
          <%= link_to user_path(@ticket.user) do %>
            <%= image_tag @ticket.user.avatar.url(:thumb), class: "profile-avatar", alt: "#{@ticket.user.name} avatar" %> &nbsp;&nbsp;<%= @ticket.user.name %>
          <% end %> asks
        </h4>
        <br>
        <blockquote>
          <%= @ticket.question %>
          <br>
          <br>
            <%= link_to lesson_path(@ticket.lesson) do %>
              <span class="glyphicon glyphicon-list"></span> &nbsp;<%= @ticket.lesson.name %>, <%= @ticket.lesson.section %>
            <% end %>
        </blockquote>
    <%= @ticket.created_at.getlocal.strftime('%I:%M:%S %p') %>
    <br>
    <% if @ticket.checked_at %>
      <%= @ticket.checked_at.getlocal.strftime('%I:%M:%S %p') %>
    <% end %>
    <br>
    <% if @ticket.closed_at %>
      <%= @ticket.closed_at.getlocal.strftime('%I:%M:%S %p') %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-sm-6 col-md-4 col-sm-offset-3 col-md-offset-4">
    <div class="thumbnail">
      <%= image_tag @user.avatar.url(:medium), class: "profile-avatar" %>
      <div class="caption text-center">
        <h2><%= @user.name %></h2>
        <p>Tickets created: <%= @user.tickets.count %></p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-6 col-md-6 col-sm-offset-3 col-md-offset-3">
    <%= render @user.tickets %>
  </div>
</div>